### ISSUE TITLE
bautajs-fastify fails trying to add a route to fastify on Windows 

### ISSUE THREAD

**Issue by santiago-perez-axa** [axa-group/bauta.js#73]
# Bug report

## Describe the bug

Using Windows I got the following error trace:

```console
:{"type":"AssertionError","message":"The first character of a path should be `/` or `*`","stack":"AssertionError [ERR_ASSERTION]: The first character of a path should be `/` or `*`
    at Router.on (Z:\\myAPI\\src\\node_modules\\find-my-way\\index.js:106:3)
    at Object.addNewRoute (Z:\\myAPI\\src\\node_modules\\fastify\\lib\\route.js:303:16)
    at Object.route (Z:\\myAPI\\src\\node_modules\\fastify\\lib\\route.js:219:19)
    at Object._route [as route] (Z:\\myAPI\\src\\node_modules\\fastify\\fastify.js:273:27)
   at addRoute (Z:\\myAPI\\src\\node_modules\\@axa\\bautajs-fastify\\src\\expose-routes.ts:175:7)
    at Z:\\myAPI\\src\\node_modules\\@axa\\bautajs-fastify\\dist\\expose-routes.js:158:13
    at Array.forEach (<anonymous>)
    at Z:\\myAPI\\src\\node_modules\\@axa\\bautajs-fastify\\src\\expose-routes.ts:203:1
    at Array.forEach (<anonymous>)\n    at exposeRoutes (Z:\\myAPI\\src\\node_modules\\@axa\\bautajs-fastify\\src\\expose-routes.ts:198:7)","generatedMessage":false,"code":"ERR_ASSERTION","actual":false,"expected":true,"operator":"=="},"msg":"Error on bautajsFastify plugin"}
```

### Expected behaviour

All the routes are adequately exposed using fastify.

### Desktop (please complete the following information):

- OS: Windows 10
- bautajs-fastify 2.1.0
- Node.js version 18.13.0

**Comment by santiago-perez-axa** [comment]
Hi, @franher. I will check and try a do a PR
